Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.boot_timeout = 900

  config.vm.define "linux" do |l|
    l.vm.hostname = "linux"
    l.vm.network "private_network", ip: "192.168.56.30"

    l.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2230, host_ip: "127.0.0.1"

    l.vm.synced_folder "..", "/projeto"

    l.vm.provider "virtualbox" do |vb|
      vb.name   = "tp1-linux"
      vb.memory = "512"
      vb.cpus   = 1
    end

    l.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nmap curl dnsutils openssh-client
    SHELL
  end
end
