Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.boot_timeout = 900

  config.vm.synced_folder "../scripts", "/scripts"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 2
  end

  config.vm.define "web1" do |web1|
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.56.12"
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.20"

    db.vm.synced_folder "../data/dados_persistentes", "/var/lib/dados_persistentes",
      create: true,
      mount_options: ["dmode=777", "fmode=666"]
  end

  config.vm.define "bastion", primary: true do |b|
    b.vm.hostname = "bastion"
    b.vm.network "private_network", ip: "192.168.56.10"

    b.vm.synced_folder "./.vagrant/machines", "/home/vagrant/machines", disabled: false
    b.vm.synced_folder "../ansible", "/ansible"

    b.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    b.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y software-properties-common
      add-apt-repository --yes --update ppa:ansible/ansible
      apt-get install -y ansible

      install -d -m 700 -o vagrant -g vagrant /home/vagrant/keys
      for maquina in web1 web2 db; do
        chave=/home/vagrant/machines/$maquina/virtualbox/private_key
        if [ -f "$chave" ]; then
          install -m 600 -o vagrant -g vagrant "$chave" /home/vagrant/keys/$maquina
        fi
      done
    SHELL

    b.vm.provision "ansible_local" do |ansible|
      ansible.install           = false
      ansible.provisioning_path = "/ansible"
      ansible.config_file       = "/ansible/ansible.cfg"
      ansible.inventory_path    = "inventory.ini"
      ansible.playbook          = "site.yml"
      ansible.limit             = "all"
    end
  end
end
